embeddings {
tensor_name: "default:00000"
tensor_path: "00000/default/tensors.tsv"
metadata_path: "00000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:01000"
tensor_path: "01000/default/tensors.tsv"
metadata_path: "01000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:02000"
tensor_path: "02000/default/tensors.tsv"
metadata_path: "02000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:03000"
tensor_path: "03000/default/tensors.tsv"
metadata_path: "03000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:04000"
tensor_path: "04000/default/tensors.tsv"
metadata_path: "04000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:05000"
tensor_path: "05000/default/tensors.tsv"
metadata_path: "05000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:06000"
tensor_path: "06000/default/tensors.tsv"
metadata_path: "06000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:07000"
tensor_path: "07000/default/tensors.tsv"
metadata_path: "07000/default/metadata.tsv"
}
embeddings {
tensor_name: "default:08000"
tensor_path: "08000/default/tensors.tsv"
metadata_path: "08000/default/metadata.tsv"
}
